### ISSUE TITLE
There are still a few console logs in source code

### ISSUE THREAD

**Issue by code-reaper08** [pranjay-poddar/Covinex#10]
Hello 👋 
I wanted to convey that, there are still few `console.log` statements, which may leak some information. I didn't remove them because they will be useful when debugging the source code.

There are `console.log` in the below files,

1.  https://github.com/pranjay-poddar/Covinex/blob/master/src/app/globe-track/globe-track.component.ts#L44
2.  https://github.com/pranjay-poddar/Covinex/blob/master/src/app/globe-track/globe-track.component.ts#L68
3.  https://github.com/pranjay-poddar/Covinex/blob/master/src/app/globe-track/globe-track.component.ts#L99
4.  https://github.com/pranjay-poddar/Covinex/blob/master/src/app/tracker/tracker.component.ts#L67
5. https://github.com/code-reaper08/Covinex/blob/master/src/app/services/data-service.service.ts#L43

**Comment by pranjay-poddar** [comment]
@code-reaper08 all the logs are been kept purposely so that contributors find it easy to understand the project flow and these logs does not contain any sensitive data which can be leaked 

Thank you for taking out time and giving this valuable feedback.

Happy Coding!

**Comment by maryanamorato** [comment]
Can you assign to me?

**Comment by maryanamorato** [comment]
btw, is this issue part of the hacktober fest?
